# Generated by Django 5.2.7 on 2025-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
